management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: '{cipher}AQCcTC63ysE6Iz2uDGQ6bD7zHUqjYz3Ycmsqowk3CZ5A7sFtta9XwLVX+HEoGoBYWS1DOMQmzrv/5NHVPAduaJDCLjdZLXDu8gkki5M8JKGXuRPHelHj+7TzFgsg73P1yLqYTmpeqNbT919Ikbt41hSTfE786k9xVh/5cSEPd5UjodDHVktg/aKoBWbWVPSBtTCYtCXsEasfloz42t+ZG31vb38U3k1Hwgven+ZkzbMX5mjareM3Me36oAy0qx/yLukXABuFRtpDSTY4x1jQGN4iRCAW8/jusnIfGQZL2tuDT+AGSWFgV45TA08t/1I4ymE+pW4dZ5DLfrvxkvhO60QCAyG2OKGplDWJ08r9MJKj2h92IzA7ptAFHoKFkePXEmc='
    password:
