management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    

commonkey1: AAAAAA
commonkey2: commonvalue2222
message: '{cipher}AQCF636zANk3hhyFY5khWGl7ZqKVphHH3oOLn7vsqgHzPPh/BAQxOb9xx+dmcI4urPYISaOPA1xfGkxZig2rB2PGmqf2kIJle7MpwwV2f/vulntOebqN3kBnCf8nLutwnfsg7vuVoC88j6/3SOLhZCJ9T7zdpgTVloqlVDfrzJPDLBr5onF3hx5g2LiHkhgCRqpfAmKOvUaLzAmCkmyKT7JevuC6ctRzvALk3WLxkc+D6ZrFnQvWNB60mioXQMLGOdLziA0ZXpjU45Oi6dCAk9SYHtfCrg2FiGwgeGJSTTLRTaMDjz0F3h+qbZEaU9sE5TW5XCx3DlI7rb//pSDgFnfdwIvD860hcDeCK6urIJEB5kIftP7r4wvT3usWnRyw3oQ='
